"use client";
import { Button } from "@/components/ui/button";
import { ArrowUp } from "lucide-react";
import React, { useState } from "react";

interface ChatInputProps {
  onSendMessage: (message: string) => void;
}

export function ChatInput({ onSendMessage }: ChatInputProps) {
  const [inputValue, setInputValue] = useState("");

  const handleSubmit = (e?: React.FormEvent) => {
    // Prevent default form submission if event is passed
    if (e) e.preventDefault();
    if (inputValue.trim() === "") return;

    // Replace single newlines with double newlines before sending
    const doubledNewlineValue = inputValue.replace(/\n/g, "\n\n");
    onSendMessage(doubledNewlineValue);

    setInputValue(""); // Clear input after sending
  };

  return (
    <div className="bg-background p-4 w-full">
      <div className="max-w-2xl mx-auto">
        <form className="relative" onSubmit={handleSubmit}>
          <textarea
            rows={1}
            placeholder="Ask Asendio..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => {
              // If user presses Enter without Shift, submit instead of adding newline.
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSubmit();
              }
            }}
            className="w-full px-4 py-3 pr-12 border rounded-2xl focus:outline-none focus:ring-2 focus:ring-[#0364E0] shadow-lg"
          />
          <Button
            type="submit"
            size="icon"
            className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg bg-[#0364E0] hover:bg-[#0c6ce9]"
          >
            <ArrowUp className="w-4 h-4 text-white" />
            <span className="sr-only">Send message</span>
          </Button>
        </form>

        <p className="mt-2 text-xs text-center text-muted-foreground">
          Messages are generated by AI and may be inaccurate or inappropriate.{" "}
          <a href="#" className="underline">
            Learn more
          </a>
        </p>
      </div>
    </div>
  );
}
